str = "i am divy chaturvedi"
'str.endswith function'
#print(str.endswith("edi"))
#print(str.endswith("fhi"))

'str.capitalize() function'  #CAPITALIZE FIRST CHARACTER
#print(str.capitalize()) 

'str.replace(old,new) function'    #replace 
#print(str.replace("am","were"))

'str.find(word)  function'  #dhundne ke liye kam aata hai kisi
                              #kisi bhi word ko
#example=
str2 = "divy ji"
#print(str2.find("y"))
'count function'
'str.count()'
#example=
str3="styuiyuiolywp"
#print(str3.count("y"))




